<?php

/**
 * @file
 * Integrates paysto redirected payment service.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uc_paysto_help($route_name, RouteMatchInterface $route_match) {
	// Provide information and instructions on the payment method add and edit forms.
	if ($route_name == 'entity.uc_payment_method.add_form' &&
	    $route_match->getRawParameter('plugin_id') == 'paysto') {
		return '<p>' . t('To accept payments in paysto, please ensure that demo mode is disabled and your store currency is one of RUB UAH USD, AUD, CAD, EUR or GBP.') . '</p>';
	}
	elseif ($route_name == 'entity.uc_payment_method.edit_form' &&
	        $route_match->getParameter('uc_payment_method')->getPlugin()->getPluginId() == 'paysto') {
		return '<p>' . t('To accept payments in paysto, please ensure that demo mode is disabled and your store currency is one of RUB UAH USD, AUD, CAD, EUR or GBP.') . '</p>';
	}
}

/**
 * Implements hook_ucga_display().
 */
function uc_paysto_ucga_display() {

	if (arg(0) == 'cart' && arg(1) == 'paysto' && arg(2) == 'complete') {
		return TRUE;
	}
}
