# Schema for the configuration files of the uc_paysto module.
payment_method.settings.paysto:
  type: mapping
  label: 'paysto form configuration settings'
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    secret_key:
      type: string
      label: 'Secret Key'
    back_url:
      type: string
      label: 'Back ref url. (http://{your_site}/paysto/back_url)'
    currency:
      type: string
      label: 'Type of currency. Leave empty to shop currency'
    language:
      type: string
      label: 'Payment Language'
    autocapture:
      type: boolean
      label: 'Autocapture'
